ip: 10.192.42.216
jupyter_info:
- launcher_path: D:\FengYiheng\.jupyter\RunJupyterNotebook.bat
  name: arch_gaussian
  port: '8890'
- launcher_path: D:\FengYiheng\Projects\ConcreteInspection\.jupyter\RunJupyterNotebook.bat
  name: concrete_inspection
  port: '8889'
name: jeremy
project_path: D:\M.Arch\MastersThesis\arch-gaussian
svn_path: D:\FengYiheng\Projects\arch-gaussian
sys_info_port: '5000'
